services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - LOOKUP_API_KEY=${LOOKUP_API_KEY:-some_key}
      - JDBC_URL=jdbc:postgresql://db:5432/startrack
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    networks:
      - startrack-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=startrack
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - startrack-network

networks:
  startrack-network:
    driver: bridge

volumes:
  postgres-data: